ProyectoHotel/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoHotel.Models
{
    public class Producto
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Detalle { get; set; }
        public decimal Precio { get; set; }
        public string PrecioTexto { get; set; }
        public int Cantidad { get; set; }
        public bool Estado { get; set; }
    }
}

ProyectoHotel/Controllers/GestionController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class GestionController : Controller
    {
        // GET: Gestion
        public ActionResult Recepcion()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Gestion
        public ActionResult RecepcionRegistro(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Habitacion objeto = HabitacionLogica.Instancia.Listar().Where(h => h.IdHabitacion == idhabitacion).FirstOrDefault();

            return View(objeto);
        }

        public ActionResult DetalleRecepcion(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion oRecepcion = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            if (oRecepcion != null)
            {

                List<Venta> oVenta = (from vn in VentaLogica.Instancia.Listar()
                                      where vn.oRecepcion.IdRecepcion == oRecepcion.IdRecepcion
                                      select new Venta()
                                      {
                                          IdVenta = vn.IdVenta,
                                          oRecepcion = new Recepcion() { IdRecepcion = vn.oRecepcion.IdRecepcion },
                                          Total = vn.Total,
                                          Estado = vn.Estado,
                                          oDetalleVenta = DetalleVentaLogica.Instancia.Listar().Where(dv => dv.IdVenta == vn.IdVenta).ToList()
                                      }).ToList();

                oRecepcion.oVenta = oVenta;
            }

            return View(oRecepcion);
        }

        // GET: Gestion
        public ActionResult Salida()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Gestion
        public ActionResult SalidaRegistro(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion oRecepcion = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            if (oRecepcion != null) {

                List<Venta> oVenta = (from vn in VentaLogica.Instancia.Listar()
                                      where vn.oRecepcion.IdRecepcion == oRecepcion.IdRecepcion
                                      select new Venta()
                                      {
                                          IdVenta = vn.IdVenta,
                                          oRecepcion = new Recepcion() { IdRecepcion = vn.oRecepcion.IdRecepcion },
                                          Total = vn.Total,
                                          Estado = vn.Estado,
                                          oDetalleVenta = DetalleVentaLogica.Instancia.Listar().Where(dv => dv.IdVenta == vn.IdVenta).ToList()
                                      }).ToList();

                oRecepcion.oVenta = oVenta;
            }

            return View(oRecepcion);
        }

        



        // GET: Gestion
        public ActionResult Venta(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion objeto = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            return View(objeto);
        }





        [HttpGet]
        public JsonResult ListarHabitacion(int idpiso)
        {
            List<Habitacion> oLista = new List<Habitacion>();
            oLista = HabitacionLogica.Instancia.Listar().Where(x => x.oPiso.IdPiso == (idpiso == 0 ? x.oPiso.IdPiso : idpiso) ).OrderBy(o => o.Numero).ToList();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult ActualizarEstadoHabitacion(int idhabitacion,int idestadohabitacion)
        {

            bool respuesta = false;
            respuesta = HabitacionLogica.Instancia.ActualizarEstado(idhabitacion, idestadohabitacion);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GuardarPersona(Recepcion objeto)
        {
            bool respuesta = false;
            respuesta = RecepcionLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarRecepcion(Recepcion objeto)
        {
            bool respuesta = false;
            objeto.Observacion = objeto.Observacion == null ? "" : objeto.Observacion;
            respuesta = RecepcionLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CerrarRecepcion(Recepcion objeto)
        {
            bool respuesta = false;
            respuesta = RecepcionLogica.Instancia.Cerrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

ProyectoHotel/Controllers/MantenimientoController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class MantenimientoController : Controller
    {
        // GET: Mantenimiento
        public ActionResult Habitaciones()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Mantenimiento
        public ActionResult Categoria()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Mantenimiento
        public ActionResult Pisos()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }



        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = CategoriaLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdCategoria == 0) ? CategoriaLogica.Instancia.Registrar(objeto) : CategoriaLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            respuesta = CategoriaLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarPiso()
        {
            List<Piso> oLista = new List<Piso>();
            oLista = PisoLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarPiso(Piso objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdPiso == 0) ? PisoLogica.Instancia.Registrar(objeto) : PisoLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarPiso(int id)
        {
            bool respuesta = false;
            respuesta = PisoLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult ListarHabitacion()
        {
            List<Habitacion> oLista = new List<Habitacion>();
            oLista = HabitacionLogica.Instancia.Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarHabitacion(Habitacion objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdHabitacion == 0) ? HabitacionLogica.Instancia.Registrar(objeto) : HabitacionLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarHabitacion(int id)
        {
            bool respuesta = false;
            respuesta = HabitacionLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

ProyectoHotel/Controllers/TiendaController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Producto()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        public ActionResult Vender()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = ProductoLogica.Instancia.Listar().OrderBy(o => o.Nombre).ToList();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarProducto(Producto objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdProducto == 0) ? ProductoLogica.Instancia.Registrar(objeto) : ProductoLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            respuesta = ProductoLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarVenta(Venta objeto)
        {
            bool respuesta = false;
            respuesta = VentaLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

    }
}

ProyectoHotel/Views/Tienda/Producto.cshtml
@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Productos</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <button class="btn btn-success btn-sm" type="button" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered" id="tabla" style="width:100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Detalle</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Estado</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Nombre</th>
                                <th>Detalle</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Estado</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="FormModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLabel">Producto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input id="txtid" type="hidden" value="0" />
                <form id="formNivel">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtnombre">Nombre:</label>
                                <input type="text" class="form-control required" id="txtnombre" name="descripcion" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtdetalle">Detalle:</label>
                                <input type="text" class="form-control required" id="txtdetalle" name="descripcion" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtprecio">Precio:</label>
                                <input type="text" class="form-control required" id="txtprecio" name="descripcion" autocomplete="off">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtcantidad">Cantidad:</label>
                                <input type="text" class="form-control required" id="txtcantidad" name="descripcion" autocomplete="off">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="cboEstado">Estado:</label>
                                <select id="cboEstado" class="form-control">
                                    <option value="1">Activo</option>
                                    <option value="0">No Activo</option>
                                </select>
                            </div>
                        </div>
                    </div>

                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script>
        var tabladata;

        $(document).ready(function () {


                tabladata = $('#tabla').DataTable({
                    responsive:true,
                    "ajax": {
                        "url": '@Url.Action("ListarProducto", "Tienda")',
                        "type": "GET",
                        "datatype": "json"
                    },
                    "columns": [
                        { "data": "Nombre" },
                        { "data": "Detalle" },
                        { "data": "Precio" },
                        { "data": "Cantidad" },
                        {
                            "data": "Estado", "render": function (data) {
                                if (data) {
                                    return '<span class="badge badge-success p-2">Activo</span>'
                                } else {
                                    return '<span class="badge badge-danger p-2">No Activo</span>'
                                }
                            }
                        },
                        {
                            "data": "IdProducto", "render": function (data, type, row, meta) {

                                return $("<button>").addClass("btn btn-primary btn-editar btn-sm").append(
                                    $("<i>").addClass("fas fa-pen")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML
                                +
                                $("<button>").addClass("btn btn-danger btn-eliminar btn-sm ml-2").append(
                                    $("<i>").addClass("fas fa-trash")
                                ).attr({ "data-informacion": JSON.stringify(row) })[0].outerHTML;

                            },
                            "orderable": false,
                            "searchable": false,
                            "width": "90px"
                        }

                    ],
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                    }
                });
        });



        $(document).on('click', '.btn-editar', function (event) {
            var json = $(this).data("informacion")

            abrirModal(json)
        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtnombre").val("");
            $("#txtdetalle").val("");
            $("#txtprecio").val("");
            $("#txtcantidad").val("");
            $("#cboEstado").val(1);

            if (json != null) {

                $("#txtid").val(json.IdProducto);
                $("#txtnombre").val(json.Nombre);
                $("#txtdetalle").val(json.Detalle);
                $("#txtprecio").val(json.Precio);
                $("#txtcantidad").val(json.Cantidad);
                $("#cboEstado").val(json.Estado == true ? 1 : 0);
            }

            $('#FormModal').modal('show');
        }

        $(document).on('click', '.btn-eliminar', function (event) {
            var json = $(this).data("informacion")

            jQuery.ajax({
                url: '@Url.Action("EliminarProducto", "Tienda")',
                type: "POST",
                data: JSON.stringify({ id: json.IdProducto}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                    } else {
                        alert("No se pudo eliminar")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });
        });

        function Guardar() {
            var request = {
                objeto: {
                    IdProducto: $("#txtid").val(),
                    Nombre: $("#txtnombre").val(),
                    Detalle: $("#txtdetalle").val(),
                    PrecioTexto: $("#txtprecio").val(),
                    Cantidad: $("#txtcantidad").val(),
                    Estado: parseInt($("#cboEstado").val()) == 1 ? true : false
                }
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarProducto", "Tienda")',
                type: "POST",
                data: JSON.stringify(request),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabladata.ajax.reload();
                        $('#FormModal').modal('hide');
                    } else {
                        alert("No se pudo guardar los cambios")
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                },
            });

        }

    </script>

}

ProyectoHotel/Views/Tienda/Vender.cshtml
@{
    ViewBag.Title = "Vender";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-body">
        <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Seleccionar Piso</label>
            <div class="col-sm-4">
                <select class="form-control" id="cbopiso"></select>
            </div>
        </div>
        <hr />
        <div id="habitaciones" class="row">


        </div>
    </div>
</div>


@section scripts{

    <script>
        var tabladata;

        $(document).ready(function () {

            jQuery.ajax({
                url: '@Url.Action("ListarPiso", "Mantenimiento")',
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("<option>").attr({ "value": "0"}).text("Todos").appendTo("#cbopiso");

                    $.each(data.data, function (index, value) {
                        $("<option>").attr({ "value": value.IdPiso }).text(value.Descripcion).appendTo("#cbopiso");
                    });
                    $("#cbopiso").val($("#cbopiso option:first").val());
                    $("#cbopiso").trigger("change");
                },
                error: function (error) {
                    console.log(error)
                }
            });


        });

        $("#cbopiso").on("change", function (e) {

            jQuery.ajax({
                url: '@Url.Action("ListarHabitacion", "Gestion")' + '?idpiso=' + $("#cbopiso option:selected").val() ,
                type: "GET",
                data: null,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $("#habitaciones").html("");
                    $.each(data.data, function (index, value) {
                        if (value.oEstadoHabitacion.IdEstadoHabitacion == 2) {
                            var clase = "";
                            var icono = "";
                            switch (value.oEstadoHabitacion.IdEstadoHabitacion) {
                                case 1:
                                    clase = "success";
                                    icono = "fas fa-box";
                                    break;
                                case 2:
                                    clase = "warning";
                                    icono = "fas fa-bed";
                                    break;
                                default:
                                    clase = "info";
                                    icono = "fas fa-air-freshener";
                            }

                            $("<div>").addClass("col-xl-3 col-md-6 mb-4").append(
                                $("<div>").addClass("card border-" + clase + " rounded-0").append(
                                    $("<div>").addClass("card-body").append(
                                        $("<div>").addClass("row no-gutters align-items-center").append(
                                            $("<div>").addClass("col mr-2").append(
                                                $("<div>").addClass("h5 mb-0 font-weight-bold text-gray-800").text("NRO: " + value.Numero),
                                                $("<div>").addClass("text-xs font-weight-bold text-" + clase + " text-uppercase mb-1 mt-1").text("Categoria: " + value.oCategoria.Descripcion),
                                            ),
                                            $("<div>").addClass("col-auto").append(
                                                $("<i>").addClass(icono + " fa-2x text-" + clase)
                                            )
                                        )
                                    ),
                                    $("<div>").addClass("card-footer d-flex bg-" + clase + " align-items-center justify-content-between rounded-0").append(
                                        $("<a>").addClass("small text-white stretched-link text-uppercase font-weight-bold select-habitacion").text("Iniciar Venta").data("info", JSON.stringify({ idhabitacion: value.IdHabitacion, idestadohabitacion: value.oEstadoHabitacion.IdEstadoHabitacion })),
                                        $("<div>").addClass("small text-white").append($("<i>").addClass("fas fa-angle-right"))
                                    )
                                )
                            ).appendTo("#habitaciones");
                        }




                    });


                },
                error: function (error) {
                    console.log(error)
                }
            });

        })


        $(document).on('click', '.select-habitacion', function (event) {
            var json = JSON.parse( $(this).data("info"))
            window.location.href = "@Url.Action("Venta", "Gestion")" + "?idhabitacion=" + json.idhabitacion;
        });




    </script>

}