ProyectoHotel/Controllers/GestionController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class GestionController : Controller
    {
        // GET: Gestion
        public ActionResult Recepcion()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Gestion
        public ActionResult RecepcionRegistro(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Habitacion objeto = HabitacionLogica.Instancia.Listar().Where(h => h.IdHabitacion == idhabitacion).FirstOrDefault();

            return View(objeto);
        }

        public ActionResult DetalleRecepcion(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion oRecepcion = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            if (oRecepcion != null)
            {

                List<Venta> oVenta = (from vn in VentaLogica.Instancia.Listar()
                                      where vn.oRecepcion.IdRecepcion == oRecepcion.IdRecepcion
                                      select new Venta()
                                      {
                                          IdVenta = vn.IdVenta,
                                          oRecepcion = new Recepcion() { IdRecepcion = vn.oRecepcion.IdRecepcion },
                                          Total = vn.Total,
                                          Estado = vn.Estado,
                                          oDetalleVenta = DetalleVentaLogica.Instancia.Listar().Where(dv => dv.IdVenta == vn.IdVenta).ToList()
                                      }).ToList();

                oRecepcion.oVenta = oVenta;
            }

            return View(oRecepcion);
        }

        // GET: Gestion
        public ActionResult Salida()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Gestion
        public ActionResult SalidaRegistro(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion oRecepcion = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            if (oRecepcion != null) {

                List<Venta> oVenta = (from vn in VentaLogica.Instancia.Listar()
                                      where vn.oRecepcion.IdRecepcion == oRecepcion.IdRecepcion
                                      select new Venta()
                                      {
                                          IdVenta = vn.IdVenta,
                                          oRecepcion = new Recepcion() { IdRecepcion = vn.oRecepcion.IdRecepcion },
                                          Total = vn.Total,
                                          Estado = vn.Estado,
                                          oDetalleVenta = DetalleVentaLogica.Instancia.Listar().Where(dv => dv.IdVenta == vn.IdVenta).ToList()
                                      }).ToList();

                oRecepcion.oVenta = oVenta;
            }

            return View(oRecepcion);
        }

        



        // GET: Gestion
        public ActionResult Venta(int idhabitacion)
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            Recepcion objeto = RecepcionLogica.Instancia.Listar().Where(h => h.oHabitacion.IdHabitacion == idhabitacion && h.Estado == true).FirstOrDefault();

            return View(objeto);
        }





        [HttpGet]
        public JsonResult ListarHabitacion(int idpiso)
        {
            List<Habitacion> oLista = new List<Habitacion>();
            oLista = HabitacionLogica.Instancia.Listar().Where(x => x.oPiso.IdPiso == (idpiso == 0 ? x.oPiso.IdPiso : idpiso) ).OrderBy(o => o.Numero).ToList();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult ActualizarEstadoHabitacion(int idhabitacion,int idestadohabitacion)
        {

            bool respuesta = false;
            respuesta = HabitacionLogica.Instancia.ActualizarEstado(idhabitacion, idestadohabitacion);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GuardarPersona(Recepcion objeto)
        {
            bool respuesta = false;
            respuesta = RecepcionLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarRecepcion(Recepcion objeto)
        {
            bool respuesta = false;
            objeto.Observacion = objeto.Observacion == null ? "" : objeto.Observacion;
            respuesta = RecepcionLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CerrarRecepcion(Recepcion objeto)
        {
            bool respuesta = false;
            respuesta = RecepcionLogica.Instancia.Cerrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
    }
}

ProyectoHotel/Controllers/InicioController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult Index()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Inicio
        public ActionResult Usuario()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        // GET: Inicio
        public ActionResult Cliente()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        [HttpGet]
        public JsonResult ListarTipoPersona()
        {
            List<TipoPersona> oLista = new List<TipoPersona>();
            oLista = PersonaLogica.Instancia.ListarTipoPersona();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ListarPersona()
        {
            List<Persona> oLista = new List<Persona>();

            oLista = PersonaLogica.Instancia.Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarPersona(Persona objeto)
        {
            bool respuesta = false;
            objeto.Clave = objeto.Clave == null ? "" : objeto.Clave;
            objeto.TipoDocumento = objeto.TipoDocumento == null ? "" : objeto.TipoDocumento;
            respuesta = (objeto.IdPersona == 0) ? PersonaLogica.Instancia.Registrar(objeto) : PersonaLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarPersona(int id)
        {
            bool respuesta = false;
            respuesta = PersonaLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CerrarSesion()
        {
            Session["Usuario"] = null;
            return RedirectToAction("Index", "Login");
        }
    }
}

ProyectoHotel/Controllers/ReporteController.cs
using ClosedXML.Excel;
using ProyectoHotel.Logica;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Productos()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        public ActionResult Recepciones()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        [HttpPost]
        public FileResult ExportarProductos(string estado,string fechainicio, string fechafin)
        {

            DataTable dt = ReporteLogica.Instancia.Productos(estado,fechainicio,fechafin);

            dt.TableName = "Datos";
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Reporte Productos " + DateTime.Now.ToString() + ".xlsx");
                }
            }
        }

        [HttpPost]
        public FileResult ExportarRecepciones(string idhabitacion, string fechainicio, string fechafin)
        {

            DataTable dt = ReporteLogica.Instancia.Recepciones(idhabitacion, fechainicio, fechafin);

            dt.TableName = "Datos";
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Reporte Recepciones " + DateTime.Now.ToString() + ".xlsx");
                }
            }
        }
    }
}

ProyectoHotel/Controllers/TiendaController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Producto()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        public ActionResult Vender()
        {
            if (Session["Usuario"] == null)
                return RedirectToAction("Index", "Login");

            return View();
        }

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = ProductoLogica.Instancia.Listar().OrderBy(o => o.Nombre).ToList();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GuardarProducto(Producto objeto)
        {
            bool respuesta = false;
            respuesta = (objeto.IdProducto == 0) ? ProductoLogica.Instancia.Registrar(objeto) : ProductoLogica.Instancia.Modificar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            respuesta = ProductoLogica.Instancia.Eliminar(id);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult RegistrarVenta(Venta objeto)
        {
            bool respuesta = false;
            respuesta = VentaLogica.Instancia.Registrar(objeto);
            return Json(new { resultado = respuesta }, JsonRequestBehavior.AllowGet);
        }

    }
}

ProyectoHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Blank</title>
    <!-- Custom fonts for this template-->
    @Styles.Render("~/Content/css")
    <style>
        a {
            cursor:pointer;
        }
        .dt-bootstrap4 {
            font-size: 14px !important;
        }
        .card-footer {
            border-top: 0px !important;
        }
    </style>
</head>
<body id="page-top">
    @{
        ProyectoHotel.Models.Persona objeto = ((ProyectoHotel.Models.Persona)Session["Usuario"]);
    }
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Inicio")">
                <div class="sidebar-brand-icon">
                    <i class="far fa-building"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Mi Hotel</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Inicio")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-concierge-bell"></i>
                    <span>Gestion</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Recepcion", "Gestion")">Recepción</a>
                        <a class="collapse-item" href="@Url.Action("Salida", "Gestion")">Salida</a>
                    </div>
                </div>
            </li>
            <!-- Nav Item - Utilities Collapse Menu -->
            @{

                if (objeto.oTipoPersona.IdTipoPersona == 1)
                {
                    <li class="nav-item">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                           aria-expanded="true" aria-controls="collapseUtilities">
                            <i class="fas fa-fax"></i>
                            <span>Tienda</span>
                        </a>
                        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                             data-parent="#accordionSidebar">
                            <div class="bg-white py-2 collapse-inner rounded">
                                <a class="collapse-item" href="@Url.Action("Vender", "Tienda")">Vender</a>
                                <h6 class="collapse-header">Registrar:</h6>
                                <a class="collapse-item" href="@Url.Action("Producto", "Tienda")">Productos</a>
                            </div>
                        </div>
                    </li>

                    <!-- Nav Item - Pages Collapse Menu -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseamantenimiento"
                           aria-expanded="true" aria-controls="collapseamantenimiento">
                            <i class="fas fa-fw fa-wrench"></i>
                            <span>Mantenimiento</span>
                        </a>
                        <div id="collapseamantenimiento" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                            <div class="bg-white py-2 collapse-inner rounded">
                                <a class="collapse-item" href="@Url.Action("Habitaciones", "Mantenimiento")">Habitaciones</a>
                                <a class="collapse-item" href="@Url.Action("Categoria", "Mantenimiento")">Categoria</a>
                                <a class="collapse-item" href="@Url.Action("Pisos", "Mantenimiento")">Pisos</a>
                            </div>
                        </div>
                    </li>
                }
            }



            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReporte"
                   aria-expanded="true" aria-controls="collapseReporte">
                    <i class="fas fa-chart-line"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReporte" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Recepciones", "Reporte")">Recepciones</a>
                        <a class="collapse-item" href="@Url.Action("Productos", "Reporte")">Productos</a>
                    </div>
                </div>
            </li>

            @{
                if (objeto.oTipoPersona.IdTipoPersona == 1)
                {
                    <!-- Nav Item - Charts -->
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Usuario","Inicio")">
                            <i class="fas fa-user-shield"></i>
                            <span>Usuarios</span>
                        </a>
                    </li>
                }
            }


            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Cliente","Inicio")">
                    <i class="fas fa-user-friends"></i>
                    <span>Clientes</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="https://www.youtube.com/channel/UCEejesXPRq3gMkh8NdmO8dg" target="_blank">
                    <i class="fas fa-donate"></i>
                    <span>Luis Fernando Youtube</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@(objeto.Nombre + " " + objeto.Apellido )</span>
                                <i class="fas fa-user-shield" style="font-size:25px;font-weight:bold"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("CerrarSesion","Inicio")">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>