ProyectoHotel/Controllers/LoginController.cs
using ProyectoHotel.Logica;
using ProyectoHotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoHotel.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string correo, string clave)
        {

            Persona ousuario = PersonaLogica.Instancia.Listar().Where(u => u.Correo == correo && u.Clave == clave && u.oTipoPersona.IdTipoPersona != 3).FirstOrDefault();

            if (ousuario == null)
            {
                ViewBag.Error = "Usuario o contraseña no correcta";
                return View();
            }

            Session["Usuario"] = ousuario;

            return RedirectToAction("Index", "Inicio");
        }
    }
}

ProyectoHotel/Views/Login/Index.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")
    <style>
    </style>
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-6">
                                <img src="@Url.Content("~/Imagenes/Hotel.jpg")" style="width: 100%;height: 500px;" class="border-right border-primary" />
                            </div>
                            <div class="col-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                                    </div>
                                    <form class="user" action="@Url.Action("Index","Login")" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" name="correo" placeholder="Email" value="Konoe@gmail.com">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="clave" placeholder="Password" value="123">
                                        </div>
                                        <div class="form-group">
                                            @{if (ViewBag.Error != null)
                                                {
                                                    <div class="alert alert-danger" role="alert">
                                                        @ViewBag.Error
                                                    </div>
                                                }
                                            }
                                        </div>
                                        <button class="btn btn-primary btn-block btn-user" type="submit">Ingresar</button>

                                    </form>
                                    <hr>
                                    <div class="text-center justify-content-center">
                                        <p class="text-primary mb-0"> &copy;<a href="" target="_blank" class="text-danger ml-1"><b></b></a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>